//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEV.MVC.ProdutoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRODUTO", Namespace="http://schemas.datacontract.org/2004/07/Dev.Service")]
    [System.SerializableAttribute()]
    public partial class PRODUTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATAHORACRIACAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QUANTIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATAHORACRIACAO {
            get {
                return this.DATAHORACRIACAOField;
            }
            set {
                if ((this.DATAHORACRIACAOField.Equals(value) != true)) {
                    this.DATAHORACRIACAOField = value;
                    this.RaisePropertyChanged("DATAHORACRIACAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOME {
            get {
                return this.NOMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMEField, value) != true)) {
                    this.NOMEField = value;
                    this.RaisePropertyChanged("NOME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QUANTIDADE {
            get {
                return this.QUANTIDADEField;
            }
            set {
                if ((this.QUANTIDADEField.Equals(value) != true)) {
                    this.QUANTIDADEField = value;
                    this.RaisePropertyChanged("QUANTIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((this.VALORField.Equals(value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProdutoService.IProdutoService")]
    public interface IProdutoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/listarProdutos", ReplyAction="http://tempuri.org/IProdutoService/listarProdutosResponse")]
        System.Collections.Generic.List<DEV.MVC.ProdutoService.PRODUTO> listarProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/listarProdutos", ReplyAction="http://tempuri.org/IProdutoService/listarProdutosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.MVC.ProdutoService.PRODUTO>> listarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/obterProduto", ReplyAction="http://tempuri.org/IProdutoService/obterProdutoResponse")]
        DEV.MVC.ProdutoService.PRODUTO obterProduto(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/obterProduto", ReplyAction="http://tempuri.org/IProdutoService/obterProdutoResponse")]
        System.Threading.Tasks.Task<DEV.MVC.ProdutoService.PRODUTO> obterProdutoAsync(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/excluirProduto", ReplyAction="http://tempuri.org/IProdutoService/excluirProdutoResponse")]
        void excluirProduto(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/excluirProduto", ReplyAction="http://tempuri.org/IProdutoService/excluirProdutoResponse")]
        System.Threading.Tasks.Task excluirProdutoAsync(int idProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/salvarProduto", ReplyAction="http://tempuri.org/IProdutoService/salvarProdutoResponse")]
        void salvarProduto(int idProduto, string nome, string valor, string quantidade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdutoService/salvarProduto", ReplyAction="http://tempuri.org/IProdutoService/salvarProdutoResponse")]
        System.Threading.Tasks.Task salvarProdutoAsync(int idProduto, string nome, string valor, string quantidade);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutoServiceChannel : DEV.MVC.ProdutoService.IProdutoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutoServiceClient : System.ServiceModel.ClientBase<DEV.MVC.ProdutoService.IProdutoService>, DEV.MVC.ProdutoService.IProdutoService {
        
        public ProdutoServiceClient() {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DEV.MVC.ProdutoService.PRODUTO> listarProdutos() {
            return base.Channel.listarProdutos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.MVC.ProdutoService.PRODUTO>> listarProdutosAsync() {
            return base.Channel.listarProdutosAsync();
        }
        
        public DEV.MVC.ProdutoService.PRODUTO obterProduto(int idProduto) {
            return base.Channel.obterProduto(idProduto);
        }
        
        public System.Threading.Tasks.Task<DEV.MVC.ProdutoService.PRODUTO> obterProdutoAsync(int idProduto) {
            return base.Channel.obterProdutoAsync(idProduto);
        }
        
        public void excluirProduto(int idProduto) {
            base.Channel.excluirProduto(idProduto);
        }
        
        public System.Threading.Tasks.Task excluirProdutoAsync(int idProduto) {
            return base.Channel.excluirProdutoAsync(idProduto);
        }
        
        public void salvarProduto(int idProduto, string nome, string valor, string quantidade) {
            base.Channel.salvarProduto(idProduto, nome, valor, quantidade);
        }
        
        public System.Threading.Tasks.Task salvarProdutoAsync(int idProduto, string nome, string valor, string quantidade) {
            return base.Channel.salvarProdutoAsync(idProduto, nome, valor, quantidade);
        }
    }
}
