//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pagamento.UsuarioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioService.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/listarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/listarUsuariosResponse")]
        Dev.Service.USUARIO[] listarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/listarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/listarUsuariosResponse")]
        System.Threading.Tasks.Task<Dev.Service.USUARIO[]> listarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/obterCliente", ReplyAction="http://tempuri.org/IUsuarioService/obterClienteResponse")]
        Dev.Service.USUARIO obterCliente(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/obterCliente", ReplyAction="http://tempuri.org/IUsuarioService/obterClienteResponse")]
        System.Threading.Tasks.Task<Dev.Service.USUARIO> obterClienteAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/excluirUsuario", ReplyAction="http://tempuri.org/IUsuarioService/excluirUsuarioResponse")]
        void excluirUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/excluirUsuario", ReplyAction="http://tempuri.org/IUsuarioService/excluirUsuarioResponse")]
        System.Threading.Tasks.Task excluirUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/salvarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/salvarUsuarioResponse")]
        void salvarUsuario(int idUsuario, string usuarioLogin, string senha, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/salvarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/salvarUsuarioResponse")]
        System.Threading.Tasks.Task salvarUsuarioAsync(int idUsuario, string usuarioLogin, string senha, string nivel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : Pagamento.UsuarioService.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<Pagamento.UsuarioService.IUsuarioService>, Pagamento.UsuarioService.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dev.Service.USUARIO[] listarUsuarios() {
            return base.Channel.listarUsuarios();
        }
        
        public System.Threading.Tasks.Task<Dev.Service.USUARIO[]> listarUsuariosAsync() {
            return base.Channel.listarUsuariosAsync();
        }
        
        public Dev.Service.USUARIO obterCliente(int idUsuario) {
            return base.Channel.obterCliente(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Dev.Service.USUARIO> obterClienteAsync(int idUsuario) {
            return base.Channel.obterClienteAsync(idUsuario);
        }
        
        public void excluirUsuario(int idUsuario) {
            base.Channel.excluirUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task excluirUsuarioAsync(int idUsuario) {
            return base.Channel.excluirUsuarioAsync(idUsuario);
        }
        
        public void salvarUsuario(int idUsuario, string usuarioLogin, string senha, string nivel) {
            base.Channel.salvarUsuario(idUsuario, usuarioLogin, senha, nivel);
        }
        
        public System.Threading.Tasks.Task salvarUsuarioAsync(int idUsuario, string usuarioLogin, string senha, string nivel) {
            return base.Channel.salvarUsuarioAsync(idUsuario, usuarioLogin, senha, nivel);
        }
    }
}
