//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEV.WEB.PagamentoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REGISTROVENDA", Namespace="http://schemas.datacontract.org/2004/07/Dev.Service")]
    [System.SerializableAttribute()]
    public partial class REGISTROVENDA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOREFERENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATACANCELAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DATAHORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDPRODUTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> INATIVAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QUANTIDADEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOREFERENCIA {
            get {
                return this.CODIGOREFERENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOREFERENCIAField, value) != true)) {
                    this.CODIGOREFERENCIAField = value;
                    this.RaisePropertyChanged("CODIGOREFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATACANCELAMENTO {
            get {
                return this.DATACANCELAMENTOField;
            }
            set {
                if ((this.DATACANCELAMENTOField.Equals(value) != true)) {
                    this.DATACANCELAMENTOField = value;
                    this.RaisePropertyChanged("DATACANCELAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DATAHORA {
            get {
                return this.DATAHORAField;
            }
            set {
                if ((this.DATAHORAField.Equals(value) != true)) {
                    this.DATAHORAField = value;
                    this.RaisePropertyChanged("DATAHORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPRODUTO {
            get {
                return this.IDPRODUTOField;
            }
            set {
                if ((object.ReferenceEquals(this.IDPRODUTOField, value) != true)) {
                    this.IDPRODUTOField = value;
                    this.RaisePropertyChanged("IDPRODUTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> INATIVA {
            get {
                return this.INATIVAField;
            }
            set {
                if ((this.INATIVAField.Equals(value) != true)) {
                    this.INATIVAField = value;
                    this.RaisePropertyChanged("INATIVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QUANTIDADE {
            get {
                return this.QUANTIDADEField;
            }
            set {
                if ((object.ReferenceEquals(this.QUANTIDADEField, value) != true)) {
                    this.QUANTIDADEField = value;
                    this.RaisePropertyChanged("QUANTIDADE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOField, value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.VALORField, value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REGISTROFORMAPAGAMENTO", Namespace="http://schemas.datacontract.org/2004/07/Dev.Service")]
    [System.SerializableAttribute()]
    public partial class REGISTROFORMAPAGAMENTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AUTHORIZATIONCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CARDBINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOREFERENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FORMADEPAGAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSONRETURNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSONVENDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NSUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARCELASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RETURNCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RETURNMESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AUTHORIZATIONCODE {
            get {
                return this.AUTHORIZATIONCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.AUTHORIZATIONCODEField, value) != true)) {
                    this.AUTHORIZATIONCODEField = value;
                    this.RaisePropertyChanged("AUTHORIZATIONCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CARDBIN {
            get {
                return this.CARDBINField;
            }
            set {
                if ((object.ReferenceEquals(this.CARDBINField, value) != true)) {
                    this.CARDBINField = value;
                    this.RaisePropertyChanged("CARDBIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGOREFERENCIA {
            get {
                return this.CODIGOREFERENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOREFERENCIAField, value) != true)) {
                    this.CODIGOREFERENCIAField = value;
                    this.RaisePropertyChanged("CODIGOREFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FORMADEPAGAMENTO {
            get {
                return this.FORMADEPAGAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMADEPAGAMENTOField, value) != true)) {
                    this.FORMADEPAGAMENTOField = value;
                    this.RaisePropertyChanged("FORMADEPAGAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSONRETURN {
            get {
                return this.JSONRETURNField;
            }
            set {
                if ((object.ReferenceEquals(this.JSONRETURNField, value) != true)) {
                    this.JSONRETURNField = value;
                    this.RaisePropertyChanged("JSONRETURN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JSONVENDA {
            get {
                return this.JSONVENDAField;
            }
            set {
                if ((object.ReferenceEquals(this.JSONVENDAField, value) != true)) {
                    this.JSONVENDAField = value;
                    this.RaisePropertyChanged("JSONVENDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NSU {
            get {
                return this.NSUField;
            }
            set {
                if ((object.ReferenceEquals(this.NSUField, value) != true)) {
                    this.NSUField = value;
                    this.RaisePropertyChanged("NSU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARCELAS {
            get {
                return this.PARCELASField;
            }
            set {
                if ((object.ReferenceEquals(this.PARCELASField, value) != true)) {
                    this.PARCELASField = value;
                    this.RaisePropertyChanged("PARCELAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RETURNCODE {
            get {
                return this.RETURNCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.RETURNCODEField, value) != true)) {
                    this.RETURNCODEField = value;
                    this.RaisePropertyChanged("RETURNCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RETURNMESSAGE {
            get {
                return this.RETURNMESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.RETURNMESSAGEField, value) != true)) {
                    this.RETURNMESSAGEField = value;
                    this.RaisePropertyChanged("RETURNMESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TID {
            get {
                return this.TIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TIDField, value) != true)) {
                    this.TIDField = value;
                    this.RaisePropertyChanged("TID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.VALORField, value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PagamentoService.IPagamentoService")]
    public interface IPagamentoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/obterCodigoReferencia", ReplyAction="http://tempuri.org/IPagamentoService/obterCodigoReferenciaResponse")]
        DEV.WEB.PagamentoService.REGISTROVENDA obterCodigoReferencia(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/obterCodigoReferencia", ReplyAction="http://tempuri.org/IPagamentoService/obterCodigoReferenciaResponse")]
        System.Threading.Tasks.Task<DEV.WEB.PagamentoService.REGISTROVENDA> obterCodigoReferenciaAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/listarPagamentos", ReplyAction="http://tempuri.org/IPagamentoService/listarPagamentosResponse")]
        System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROVENDA> listarPagamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/listarPagamentos", ReplyAction="http://tempuri.org/IPagamentoService/listarPagamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROVENDA>> listarPagamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/listarFormaPagamento", ReplyAction="http://tempuri.org/IPagamentoService/listarFormaPagamentoResponse")]
        System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROFORMAPAGAMENTO> listarFormaPagamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/listarFormaPagamento", ReplyAction="http://tempuri.org/IPagamentoService/listarFormaPagamentoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROFORMAPAGAMENTO>> listarFormaPagamentoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/obterPagamento", ReplyAction="http://tempuri.org/IPagamentoService/obterPagamentoResponse")]
        DEV.WEB.PagamentoService.REGISTROVENDA obterPagamento(int idReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/obterPagamento", ReplyAction="http://tempuri.org/IPagamentoService/obterPagamentoResponse")]
        System.Threading.Tasks.Task<DEV.WEB.PagamentoService.REGISTROVENDA> obterPagamentoAsync(int idReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/consultaTID", ReplyAction="http://tempuri.org/IPagamentoService/consultaTIDResponse")]
        string consultaTID(string codigoReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/consultaTID", ReplyAction="http://tempuri.org/IPagamentoService/consultaTIDResponse")]
        System.Threading.Tasks.Task<string> consultaTIDAsync(string codigoReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/excluirPagamento", ReplyAction="http://tempuri.org/IPagamentoService/excluirPagamentoResponse")]
        void excluirPagamento(int idReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/excluirPagamento", ReplyAction="http://tempuri.org/IPagamentoService/excluirPagamentoResponse")]
        System.Threading.Tasks.Task excluirPagamentoAsync(int idReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/salvarRegistroPagamento", ReplyAction="http://tempuri.org/IPagamentoService/salvarRegistroPagamentoResponse")]
        void salvarRegistroPagamento(string idCodigoReferencia, string nome, string tipo, string quantidade, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/salvarRegistroPagamento", ReplyAction="http://tempuri.org/IPagamentoService/salvarRegistroPagamentoResponse")]
        System.Threading.Tasks.Task salvarRegistroPagamentoAsync(string idCodigoReferencia, string nome, string tipo, string quantidade, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/salvarRegistroFormaPagamento", ReplyAction="http://tempuri.org/IPagamentoService/salvarRegistroFormaPagamentoResponse")]
        void salvarRegistroFormaPagamento(string idCodigoReferencia, string valor, string parcelas, string formaPagamento, string returnCode, string returnMessage, string tid, string nsu, string cardbin, string authorizationCode, string jsonvenda, string jsonreturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/salvarRegistroFormaPagamento", ReplyAction="http://tempuri.org/IPagamentoService/salvarRegistroFormaPagamentoResponse")]
        System.Threading.Tasks.Task salvarRegistroFormaPagamentoAsync(string idCodigoReferencia, string valor, string parcelas, string formaPagamento, string returnCode, string returnMessage, string tid, string nsu, string cardbin, string authorizationCode, string jsonvenda, string jsonreturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/cancelarVenda", ReplyAction="http://tempuri.org/IPagamentoService/cancelarVendaResponse")]
        void cancelarVenda(int codreferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPagamentoService/cancelarVenda", ReplyAction="http://tempuri.org/IPagamentoService/cancelarVendaResponse")]
        System.Threading.Tasks.Task cancelarVendaAsync(int codreferencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPagamentoServiceChannel : DEV.WEB.PagamentoService.IPagamentoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagamentoServiceClient : System.ServiceModel.ClientBase<DEV.WEB.PagamentoService.IPagamentoService>, DEV.WEB.PagamentoService.IPagamentoService {
        
        public PagamentoServiceClient() {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagamentoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DEV.WEB.PagamentoService.REGISTROVENDA obterCodigoReferencia(string codigo) {
            return base.Channel.obterCodigoReferencia(codigo);
        }
        
        public System.Threading.Tasks.Task<DEV.WEB.PagamentoService.REGISTROVENDA> obterCodigoReferenciaAsync(string codigo) {
            return base.Channel.obterCodigoReferenciaAsync(codigo);
        }
        
        public System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROVENDA> listarPagamentos() {
            return base.Channel.listarPagamentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROVENDA>> listarPagamentosAsync() {
            return base.Channel.listarPagamentosAsync();
        }
        
        public System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROFORMAPAGAMENTO> listarFormaPagamento() {
            return base.Channel.listarFormaPagamento();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.WEB.PagamentoService.REGISTROFORMAPAGAMENTO>> listarFormaPagamentoAsync() {
            return base.Channel.listarFormaPagamentoAsync();
        }
        
        public DEV.WEB.PagamentoService.REGISTROVENDA obterPagamento(int idReferencia) {
            return base.Channel.obterPagamento(idReferencia);
        }
        
        public System.Threading.Tasks.Task<DEV.WEB.PagamentoService.REGISTROVENDA> obterPagamentoAsync(int idReferencia) {
            return base.Channel.obterPagamentoAsync(idReferencia);
        }
        
        public string consultaTID(string codigoReferencia) {
            return base.Channel.consultaTID(codigoReferencia);
        }
        
        public System.Threading.Tasks.Task<string> consultaTIDAsync(string codigoReferencia) {
            return base.Channel.consultaTIDAsync(codigoReferencia);
        }
        
        public void excluirPagamento(int idReferencia) {
            base.Channel.excluirPagamento(idReferencia);
        }
        
        public System.Threading.Tasks.Task excluirPagamentoAsync(int idReferencia) {
            return base.Channel.excluirPagamentoAsync(idReferencia);
        }
        
        public void salvarRegistroPagamento(string idCodigoReferencia, string nome, string tipo, string quantidade, string valor) {
            base.Channel.salvarRegistroPagamento(idCodigoReferencia, nome, tipo, quantidade, valor);
        }
        
        public System.Threading.Tasks.Task salvarRegistroPagamentoAsync(string idCodigoReferencia, string nome, string tipo, string quantidade, string valor) {
            return base.Channel.salvarRegistroPagamentoAsync(idCodigoReferencia, nome, tipo, quantidade, valor);
        }
        
        public void salvarRegistroFormaPagamento(string idCodigoReferencia, string valor, string parcelas, string formaPagamento, string returnCode, string returnMessage, string tid, string nsu, string cardbin, string authorizationCode, string jsonvenda, string jsonreturn) {
            base.Channel.salvarRegistroFormaPagamento(idCodigoReferencia, valor, parcelas, formaPagamento, returnCode, returnMessage, tid, nsu, cardbin, authorizationCode, jsonvenda, jsonreturn);
        }
        
        public System.Threading.Tasks.Task salvarRegistroFormaPagamentoAsync(string idCodigoReferencia, string valor, string parcelas, string formaPagamento, string returnCode, string returnMessage, string tid, string nsu, string cardbin, string authorizationCode, string jsonvenda, string jsonreturn) {
            return base.Channel.salvarRegistroFormaPagamentoAsync(idCodigoReferencia, valor, parcelas, formaPagamento, returnCode, returnMessage, tid, nsu, cardbin, authorizationCode, jsonvenda, jsonreturn);
        }
        
        public void cancelarVenda(int codreferencia) {
            base.Channel.cancelarVenda(codreferencia);
        }
        
        public System.Threading.Tasks.Task cancelarVendaAsync(int codreferencia) {
            return base.Channel.cancelarVendaAsync(codreferencia);
        }
    }
}
