//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEV.UsuarioService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://schemas.datacontract.org/2004/07/Dev.Service")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DATACRIACAOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NIVELField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SENHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIO1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DATACRIACAO {
            get {
                return this.DATACRIACAOField;
            }
            set {
                if ((this.DATACRIACAOField.Equals(value) != true)) {
                    this.DATACRIACAOField = value;
                    this.RaisePropertyChanged("DATACRIACAO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NIVEL {
            get {
                return this.NIVELField;
            }
            set {
                if ((this.NIVELField.Equals(value) != true)) {
                    this.NIVELField = value;
                    this.RaisePropertyChanged("NIVEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SENHA {
            get {
                return this.SENHAField;
            }
            set {
                if ((object.ReferenceEquals(this.SENHAField, value) != true)) {
                    this.SENHAField = value;
                    this.RaisePropertyChanged("SENHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIO1 {
            get {
                return this.USUARIO1Field;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIO1Field, value) != true)) {
                    this.USUARIO1Field = value;
                    this.RaisePropertyChanged("USUARIO1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioService.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/listarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/listarUsuariosResponse")]
        System.Collections.Generic.List<DEV.UsuarioService.USUARIO> listarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/listarUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/listarUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.UsuarioService.USUARIO>> listarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/obterCliente", ReplyAction="http://tempuri.org/IUsuarioService/obterClienteResponse")]
        DEV.UsuarioService.USUARIO obterCliente(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/obterCliente", ReplyAction="http://tempuri.org/IUsuarioService/obterClienteResponse")]
        System.Threading.Tasks.Task<DEV.UsuarioService.USUARIO> obterClienteAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/excluirUsuario", ReplyAction="http://tempuri.org/IUsuarioService/excluirUsuarioResponse")]
        void excluirUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/excluirUsuario", ReplyAction="http://tempuri.org/IUsuarioService/excluirUsuarioResponse")]
        System.Threading.Tasks.Task excluirUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/salvarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/salvarUsuarioResponse")]
        void salvarUsuario(int idUsuario, string usuarioLogin, string senha, string nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/salvarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/salvarUsuarioResponse")]
        System.Threading.Tasks.Task salvarUsuarioAsync(int idUsuario, string usuarioLogin, string senha, string nivel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : DEV.UsuarioService.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<DEV.UsuarioService.IUsuarioService>, DEV.UsuarioService.IUsuarioService {
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DEV.UsuarioService.USUARIO> listarUsuarios() {
            return base.Channel.listarUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DEV.UsuarioService.USUARIO>> listarUsuariosAsync() {
            return base.Channel.listarUsuariosAsync();
        }
        
        public DEV.UsuarioService.USUARIO obterCliente(int idUsuario) {
            return base.Channel.obterCliente(idUsuario);
        }
        
        public System.Threading.Tasks.Task<DEV.UsuarioService.USUARIO> obterClienteAsync(int idUsuario) {
            return base.Channel.obterClienteAsync(idUsuario);
        }
        
        public void excluirUsuario(int idUsuario) {
            base.Channel.excluirUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task excluirUsuarioAsync(int idUsuario) {
            return base.Channel.excluirUsuarioAsync(idUsuario);
        }
        
        public void salvarUsuario(int idUsuario, string usuarioLogin, string senha, string nivel) {
            base.Channel.salvarUsuario(idUsuario, usuarioLogin, senha, nivel);
        }
        
        public System.Threading.Tasks.Task salvarUsuarioAsync(int idUsuario, string usuarioLogin, string senha, string nivel) {
            return base.Channel.salvarUsuarioAsync(idUsuario, usuarioLogin, senha, nivel);
        }
    }
}
