#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="devdb")]
	public partial class contextoDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCLIENTE(CLIENTE instance);
    partial void UpdateCLIENTE(CLIENTE instance);
    partial void DeleteCLIENTE(CLIENTE instance);
    partial void InsertUSUARIO(USUARIO instance);
    partial void UpdateUSUARIO(USUARIO instance);
    partial void DeleteUSUARIO(USUARIO instance);
    partial void InsertCARRO(CARRO instance);
    partial void UpdateCARRO(CARRO instance);
    partial void DeleteCARRO(CARRO instance);
    partial void InsertPRODUTO(PRODUTO instance);
    partial void UpdatePRODUTO(PRODUTO instance);
    partial void DeletePRODUTO(PRODUTO instance);
    partial void InsertREGISTROFORMAPAGAMENTO(REGISTROFORMAPAGAMENTO instance);
    partial void UpdateREGISTROFORMAPAGAMENTO(REGISTROFORMAPAGAMENTO instance);
    partial void DeleteREGISTROFORMAPAGAMENTO(REGISTROFORMAPAGAMENTO instance);
    partial void InsertREGISTROVENDA(REGISTROVENDA instance);
    partial void UpdateREGISTROVENDA(REGISTROVENDA instance);
    partial void DeleteREGISTROVENDA(REGISTROVENDA instance);
    #endregion
		
		public contextoDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["devdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public contextoDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contextoDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contextoDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public contextoDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CLIENTE> CLIENTE
		{
			get
			{
				return this.GetTable<CLIENTE>();
			}
		}
		
		public System.Data.Linq.Table<USUARIO> USUARIO
		{
			get
			{
				return this.GetTable<USUARIO>();
			}
		}
		
		public System.Data.Linq.Table<CARRO> CARRO
		{
			get
			{
				return this.GetTable<CARRO>();
			}
		}
		
		public System.Data.Linq.Table<PRODUTO> PRODUTO
		{
			get
			{
				return this.GetTable<PRODUTO>();
			}
		}
		
		public System.Data.Linq.Table<REGISTROFORMAPAGAMENTO> REGISTROFORMAPAGAMENTO
		{
			get
			{
				return this.GetTable<REGISTROFORMAPAGAMENTO>();
			}
		}
		
		public System.Data.Linq.Table<REGISTROVENDA> REGISTROVENDA
		{
			get
			{
				return this.GetTable<REGISTROVENDA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CLIENTE")]
	public partial class CLIENTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NOME;
		
		private string _CPF;
		
		private string _ENDERECO;
		
		private string _NUMERO;
		
		private string _ESTADO;
		
		private System.Nullable<System.DateTime> _DATAHORACRIACAO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnENDERECOChanging(string value);
    partial void OnENDERECOChanged();
    partial void OnNUMEROChanging(string value);
    partial void OnNUMEROChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnDATAHORACRIACAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATAHORACRIACAOChanged();
    #endregion
		
		public CLIENTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(50)")]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(50)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDERECO", DbType="VarChar(50)")]
		public string ENDERECO
		{
			get
			{
				return this._ENDERECO;
			}
			set
			{
				if ((this._ENDERECO != value))
				{
					this.OnENDERECOChanging(value);
					this.SendPropertyChanging();
					this._ENDERECO = value;
					this.SendPropertyChanged("ENDERECO");
					this.OnENDERECOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO", DbType="VarChar(50)")]
		public string NUMERO
		{
			get
			{
				return this._NUMERO;
			}
			set
			{
				if ((this._NUMERO != value))
				{
					this.OnNUMEROChanging(value);
					this.SendPropertyChanging();
					this._NUMERO = value;
					this.SendPropertyChanged("NUMERO");
					this.OnNUMEROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(50)")]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAHORACRIACAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATAHORACRIACAO
		{
			get
			{
				return this._DATAHORACRIACAO;
			}
			set
			{
				if ((this._DATAHORACRIACAO != value))
				{
					this.OnDATAHORACRIACAOChanging(value);
					this.SendPropertyChanging();
					this._DATAHORACRIACAO = value;
					this.SendPropertyChanged("DATAHORACRIACAO");
					this.OnDATAHORACRIACAOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIO")]
	public partial class USUARIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USUARIO1;
		
		private string _SENHA;
		
		private System.Nullable<System.DateTime> _DATACRIACAO;
		
		private System.Nullable<int> _NIVEL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSUARIO1Changing(string value);
    partial void OnUSUARIO1Changed();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    partial void OnDATACRIACAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATACRIACAOChanged();
    partial void OnNIVELChanging(System.Nullable<int> value);
    partial void OnNIVELChanged();
    #endregion
		
		public USUARIO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="USUARIO", Storage="_USUARIO1", DbType="VarChar(50)")]
		public string USUARIO1
		{
			get
			{
				return this._USUARIO1;
			}
			set
			{
				if ((this._USUARIO1 != value))
				{
					this.OnUSUARIO1Changing(value);
					this.SendPropertyChanging();
					this._USUARIO1 = value;
					this.SendPropertyChanged("USUARIO1");
					this.OnUSUARIO1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="VarChar(50)")]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATACRIACAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATACRIACAO
		{
			get
			{
				return this._DATACRIACAO;
			}
			set
			{
				if ((this._DATACRIACAO != value))
				{
					this.OnDATACRIACAOChanging(value);
					this.SendPropertyChanging();
					this._DATACRIACAO = value;
					this.SendPropertyChanged("DATACRIACAO");
					this.OnDATACRIACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIVEL", DbType="Int")]
		public System.Nullable<int> NIVEL
		{
			get
			{
				return this._NIVEL;
			}
			set
			{
				if ((this._NIVEL != value))
				{
					this.OnNIVELChanging(value);
					this.SendPropertyChanging();
					this._NIVEL = value;
					this.SendPropertyChanged("NIVEL");
					this.OnNIVELChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARRO")]
	public partial class CARRO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MODELO;
		
		private string _ANO;
		
		private string _PLACA;
		
		private string _FABRICANTE;
		
		private string _TAMANHODOTANQUE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMODELOChanging(string value);
    partial void OnMODELOChanged();
    partial void OnANOChanging(string value);
    partial void OnANOChanged();
    partial void OnPLACAChanging(string value);
    partial void OnPLACAChanged();
    partial void OnFABRICANTEChanging(string value);
    partial void OnFABRICANTEChanged();
    partial void OnTAMANHODOTANQUEChanging(string value);
    partial void OnTAMANHODOTANQUEChanged();
    #endregion
		
		public CARRO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODELO", DbType="VarChar(50)")]
		public string MODELO
		{
			get
			{
				return this._MODELO;
			}
			set
			{
				if ((this._MODELO != value))
				{
					this.OnMODELOChanging(value);
					this.SendPropertyChanging();
					this._MODELO = value;
					this.SendPropertyChanged("MODELO");
					this.OnMODELOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANO", DbType="VarChar(50)")]
		public string ANO
		{
			get
			{
				return this._ANO;
			}
			set
			{
				if ((this._ANO != value))
				{
					this.OnANOChanging(value);
					this.SendPropertyChanging();
					this._ANO = value;
					this.SendPropertyChanged("ANO");
					this.OnANOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLACA", DbType="VarChar(50)")]
		public string PLACA
		{
			get
			{
				return this._PLACA;
			}
			set
			{
				if ((this._PLACA != value))
				{
					this.OnPLACAChanging(value);
					this.SendPropertyChanging();
					this._PLACA = value;
					this.SendPropertyChanged("PLACA");
					this.OnPLACAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FABRICANTE", DbType="VarChar(50)")]
		public string FABRICANTE
		{
			get
			{
				return this._FABRICANTE;
			}
			set
			{
				if ((this._FABRICANTE != value))
				{
					this.OnFABRICANTEChanging(value);
					this.SendPropertyChanging();
					this._FABRICANTE = value;
					this.SendPropertyChanged("FABRICANTE");
					this.OnFABRICANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAMANHODOTANQUE", DbType="VarChar(50)")]
		public string TAMANHODOTANQUE
		{
			get
			{
				return this._TAMANHODOTANQUE;
			}
			set
			{
				if ((this._TAMANHODOTANQUE != value))
				{
					this.OnTAMANHODOTANQUEChanging(value);
					this.SendPropertyChanging();
					this._TAMANHODOTANQUE = value;
					this.SendPropertyChanged("TAMANHODOTANQUE");
					this.OnTAMANHODOTANQUEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUTO")]
	public partial class PRODUTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NOME;
		
		private System.Nullable<decimal> _VALOR;
		
		private System.Nullable<int> _QUANTIDADE;
		
		private System.Nullable<System.DateTime> _DATAHORACRIACAO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnVALORChanging(System.Nullable<decimal> value);
    partial void OnVALORChanged();
    partial void OnQUANTIDADEChanging(System.Nullable<int> value);
    partial void OnQUANTIDADEChanged();
    partial void OnDATAHORACRIACAOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATAHORACRIACAOChanged();
    #endregion
		
		public PRODUTO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="VarChar(50)")]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this.OnVALORChanging(value);
					this.SendPropertyChanging();
					this._VALOR = value;
					this.SendPropertyChanged("VALOR");
					this.OnVALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTIDADE", DbType="Int")]
		public System.Nullable<int> QUANTIDADE
		{
			get
			{
				return this._QUANTIDADE;
			}
			set
			{
				if ((this._QUANTIDADE != value))
				{
					this.OnQUANTIDADEChanging(value);
					this.SendPropertyChanging();
					this._QUANTIDADE = value;
					this.SendPropertyChanged("QUANTIDADE");
					this.OnQUANTIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAHORACRIACAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATAHORACRIACAO
		{
			get
			{
				return this._DATAHORACRIACAO;
			}
			set
			{
				if ((this._DATAHORACRIACAO != value))
				{
					this.OnDATAHORACRIACAOChanging(value);
					this.SendPropertyChanging();
					this._DATAHORACRIACAO = value;
					this.SendPropertyChanged("DATAHORACRIACAO");
					this.OnDATAHORACRIACAOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REGISTROFORMAPAGAMENTO")]
	public partial class REGISTROFORMAPAGAMENTO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CODIGOREFERENCIA;
		
		private string _VALOR;
		
		private string _PARCELAS;
		
		private string _FORMADEPAGAMENTO;
		
		private string _RETURNCODE;
		
		private string _RETURNMESSAGE;
		
		private string _TID;
		
		private string _NSU;
		
		private string _CARDBIN;
		
		private string _AUTHORIZATIONCODE;
		
		private string _JSONVENDA;
		
		private string _JSONRETURN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCODIGOREFERENCIAChanging(string value);
    partial void OnCODIGOREFERENCIAChanged();
    partial void OnVALORChanging(string value);
    partial void OnVALORChanged();
    partial void OnPARCELASChanging(string value);
    partial void OnPARCELASChanged();
    partial void OnFORMADEPAGAMENTOChanging(string value);
    partial void OnFORMADEPAGAMENTOChanged();
    partial void OnRETURNCODEChanging(string value);
    partial void OnRETURNCODEChanged();
    partial void OnRETURNMESSAGEChanging(string value);
    partial void OnRETURNMESSAGEChanged();
    partial void OnTIDChanging(string value);
    partial void OnTIDChanged();
    partial void OnNSUChanging(string value);
    partial void OnNSUChanged();
    partial void OnCARDBINChanging(string value);
    partial void OnCARDBINChanged();
    partial void OnAUTHORIZATIONCODEChanging(string value);
    partial void OnAUTHORIZATIONCODEChanged();
    partial void OnJSONVENDAChanging(string value);
    partial void OnJSONVENDAChanged();
    partial void OnJSONRETURNChanging(string value);
    partial void OnJSONRETURNChanged();
    #endregion
		
		public REGISTROFORMAPAGAMENTO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOREFERENCIA", DbType="VarChar(50)")]
		public string CODIGOREFERENCIA
		{
			get
			{
				return this._CODIGOREFERENCIA;
			}
			set
			{
				if ((this._CODIGOREFERENCIA != value))
				{
					this.OnCODIGOREFERENCIAChanging(value);
					this.SendPropertyChanging();
					this._CODIGOREFERENCIA = value;
					this.SendPropertyChanged("CODIGOREFERENCIA");
					this.OnCODIGOREFERENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="VarChar(50)")]
		public string VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this.OnVALORChanging(value);
					this.SendPropertyChanging();
					this._VALOR = value;
					this.SendPropertyChanged("VALOR");
					this.OnVALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARCELAS", DbType="VarChar(50)")]
		public string PARCELAS
		{
			get
			{
				return this._PARCELAS;
			}
			set
			{
				if ((this._PARCELAS != value))
				{
					this.OnPARCELASChanging(value);
					this.SendPropertyChanging();
					this._PARCELAS = value;
					this.SendPropertyChanged("PARCELAS");
					this.OnPARCELASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FORMADEPAGAMENTO", DbType="VarChar(50)")]
		public string FORMADEPAGAMENTO
		{
			get
			{
				return this._FORMADEPAGAMENTO;
			}
			set
			{
				if ((this._FORMADEPAGAMENTO != value))
				{
					this.OnFORMADEPAGAMENTOChanging(value);
					this.SendPropertyChanging();
					this._FORMADEPAGAMENTO = value;
					this.SendPropertyChanged("FORMADEPAGAMENTO");
					this.OnFORMADEPAGAMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETURNCODE", DbType="VarChar(50)")]
		public string RETURNCODE
		{
			get
			{
				return this._RETURNCODE;
			}
			set
			{
				if ((this._RETURNCODE != value))
				{
					this.OnRETURNCODEChanging(value);
					this.SendPropertyChanging();
					this._RETURNCODE = value;
					this.SendPropertyChanged("RETURNCODE");
					this.OnRETURNCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RETURNMESSAGE", DbType="VarChar(50)")]
		public string RETURNMESSAGE
		{
			get
			{
				return this._RETURNMESSAGE;
			}
			set
			{
				if ((this._RETURNMESSAGE != value))
				{
					this.OnRETURNMESSAGEChanging(value);
					this.SendPropertyChanging();
					this._RETURNMESSAGE = value;
					this.SendPropertyChanged("RETURNMESSAGE");
					this.OnRETURNMESSAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TID", DbType="VarChar(50)")]
		public string TID
		{
			get
			{
				return this._TID;
			}
			set
			{
				if ((this._TID != value))
				{
					this.OnTIDChanging(value);
					this.SendPropertyChanging();
					this._TID = value;
					this.SendPropertyChanged("TID");
					this.OnTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NSU", DbType="VarChar(50)")]
		public string NSU
		{
			get
			{
				return this._NSU;
			}
			set
			{
				if ((this._NSU != value))
				{
					this.OnNSUChanging(value);
					this.SendPropertyChanging();
					this._NSU = value;
					this.SendPropertyChanged("NSU");
					this.OnNSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARDBIN", DbType="VarChar(50)")]
		public string CARDBIN
		{
			get
			{
				return this._CARDBIN;
			}
			set
			{
				if ((this._CARDBIN != value))
				{
					this.OnCARDBINChanging(value);
					this.SendPropertyChanging();
					this._CARDBIN = value;
					this.SendPropertyChanged("CARDBIN");
					this.OnCARDBINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUTHORIZATIONCODE", DbType="VarChar(50)")]
		public string AUTHORIZATIONCODE
		{
			get
			{
				return this._AUTHORIZATIONCODE;
			}
			set
			{
				if ((this._AUTHORIZATIONCODE != value))
				{
					this.OnAUTHORIZATIONCODEChanging(value);
					this.SendPropertyChanging();
					this._AUTHORIZATIONCODE = value;
					this.SendPropertyChanged("AUTHORIZATIONCODE");
					this.OnAUTHORIZATIONCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSONVENDA", DbType="VarChar(900)")]
		public string JSONVENDA
		{
			get
			{
				return this._JSONVENDA;
			}
			set
			{
				if ((this._JSONVENDA != value))
				{
					this.OnJSONVENDAChanging(value);
					this.SendPropertyChanging();
					this._JSONVENDA = value;
					this.SendPropertyChanged("JSONVENDA");
					this.OnJSONVENDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSONRETURN", DbType="VarChar(900)")]
		public string JSONRETURN
		{
			get
			{
				return this._JSONRETURN;
			}
			set
			{
				if ((this._JSONRETURN != value))
				{
					this.OnJSONRETURNChanging(value);
					this.SendPropertyChanging();
					this._JSONRETURN = value;
					this.SendPropertyChanged("JSONRETURN");
					this.OnJSONRETURNChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REGISTROVENDA")]
	public partial class REGISTROVENDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _IDPRODUTO;
		
		private string _QUANTIDADE;
		
		private string _VALOR;
		
		private System.DateTime _DATAHORA;
		
		private string _TIPO;
		
		private string _CODIGOREFERENCIA;
		
		private System.Nullable<int> _INATIVA;
		
		private System.Nullable<System.DateTime> _DATACANCELAMENTO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnIDPRODUTOChanging(string value);
    partial void OnIDPRODUTOChanged();
    partial void OnQUANTIDADEChanging(string value);
    partial void OnQUANTIDADEChanged();
    partial void OnVALORChanging(string value);
    partial void OnVALORChanged();
    partial void OnDATAHORAChanging(System.DateTime value);
    partial void OnDATAHORAChanged();
    partial void OnTIPOChanging(string value);
    partial void OnTIPOChanged();
    partial void OnCODIGOREFERENCIAChanging(string value);
    partial void OnCODIGOREFERENCIAChanged();
    partial void OnINATIVAChanging(System.Nullable<int> value);
    partial void OnINATIVAChanged();
    partial void OnDATACANCELAMENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnDATACANCELAMENTOChanged();
    #endregion
		
		public REGISTROVENDA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPRODUTO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDPRODUTO
		{
			get
			{
				return this._IDPRODUTO;
			}
			set
			{
				if ((this._IDPRODUTO != value))
				{
					this.OnIDPRODUTOChanging(value);
					this.SendPropertyChanging();
					this._IDPRODUTO = value;
					this.SendPropertyChanged("IDPRODUTO");
					this.OnIDPRODUTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTIDADE", DbType="VarChar(50)")]
		public string QUANTIDADE
		{
			get
			{
				return this._QUANTIDADE;
			}
			set
			{
				if ((this._QUANTIDADE != value))
				{
					this.OnQUANTIDADEChanging(value);
					this.SendPropertyChanging();
					this._QUANTIDADE = value;
					this.SendPropertyChanged("QUANTIDADE");
					this.OnQUANTIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR", DbType="VarChar(50)")]
		public string VALOR
		{
			get
			{
				return this._VALOR;
			}
			set
			{
				if ((this._VALOR != value))
				{
					this.OnVALORChanging(value);
					this.SendPropertyChanging();
					this._VALOR = value;
					this.SendPropertyChanged("VALOR");
					this.OnVALORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATAHORA", DbType="DateTime NOT NULL")]
		public System.DateTime DATAHORA
		{
			get
			{
				return this._DATAHORA;
			}
			set
			{
				if ((this._DATAHORA != value))
				{
					this.OnDATAHORAChanging(value);
					this.SendPropertyChanging();
					this._DATAHORA = value;
					this.SendPropertyChanged("DATAHORA");
					this.OnDATAHORAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(50)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this.OnTIPOChanging(value);
					this.SendPropertyChanging();
					this._TIPO = value;
					this.SendPropertyChanged("TIPO");
					this.OnTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGOREFERENCIA", DbType="VarChar(50)")]
		public string CODIGOREFERENCIA
		{
			get
			{
				return this._CODIGOREFERENCIA;
			}
			set
			{
				if ((this._CODIGOREFERENCIA != value))
				{
					this.OnCODIGOREFERENCIAChanging(value);
					this.SendPropertyChanging();
					this._CODIGOREFERENCIA = value;
					this.SendPropertyChanged("CODIGOREFERENCIA");
					this.OnCODIGOREFERENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INATIVA", DbType="Int")]
		public System.Nullable<int> INATIVA
		{
			get
			{
				return this._INATIVA;
			}
			set
			{
				if ((this._INATIVA != value))
				{
					this.OnINATIVAChanging(value);
					this.SendPropertyChanging();
					this._INATIVA = value;
					this.SendPropertyChanged("INATIVA");
					this.OnINATIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATACANCELAMENTO", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATACANCELAMENTO
		{
			get
			{
				return this._DATACANCELAMENTO;
			}
			set
			{
				if ((this._DATACANCELAMENTO != value))
				{
					this.OnDATACANCELAMENTOChanging(value);
					this.SendPropertyChanging();
					this._DATACANCELAMENTO = value;
					this.SendPropertyChanged("DATACANCELAMENTO");
					this.OnDATACANCELAMENTOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
